#!/usr/bin/env python3
"""Generate interactive Three.js evidence widgets for Pain Machines figures."""

from __future__ import annotations

import html
import json
from typing import Any

Widget = dict[str, Any]

# Each widget: presets = documented cases (not generic sliders). Optional scrub = one teaching timeline.
CLINICAL: list[Widget] = [
    {
        "id": "fig-neuromatrix",
        "num": "1a",
        "title": "Neuromatrix: pain generated by the whole brain",
        "cite_url": "https://pubmed.ncbi.nlm.nih.gov/11780656/",
        "cite_label": "Melzack 2001",
        "scene": "fig-neuromatrix",
        "caption": "Melzack broke the courtroom model: the brain builds pain from signal, map, memory, stress, and expectation.",
        "blurb": (
            "Melzack's neuromatrix theory treats pain as a distributed output pattern — not a faithful "
            "meter of tissue damage. Phantom-limb pain is the proof case: the map persists after the limb is gone."
        ),
        "control_prompt": "Compare Melzack's cases:",
        "presets": [
            {"id": "acute", "label": "Fresh tissue injury", "hint": "Somatic input drives output"},
            {"id": "phantom", "label": "Phantom limb", "hint": "Limb absent — pain persists"},
            {"id": "stress_flare", "label": "Stress flare, no new damage", "hint": "Memory + stress alone"},
        ],
        "metrics": [
            {"id": "output", "label": "pain output", "tone": "pain"},
            {"id": "somatic", "label": "tissue signal", "tone": "gold"},
        ],
    },
    {
        "id": "fig-iasp",
        "num": "1b",
        "title": "IASP 2020: sensory and emotional are inseparable",
        "cite_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7680716/",
        "cite_label": "Raja et al. 2020",
        "scene": "fig-iasp",
        "caption": "Official medicine: pain is always sensory and emotional — not a tissue meter alone.",
        "blurb": (
            "The 2020 IASP revision defines pain as \"an unpleasant sensory and emotional experience.\" "
            "Strip either channel and you no longer have the clinical object called pain."
        ),
        "control_prompt": "What counts as pain under IASP?",
        "presets": [
            {"id": "sensory_only", "label": "Body signal only", "hint": "Fails IASP definition"},
            {"id": "iasp_pain", "label": "Full IASP pain", "hint": "Both channels required"},
            {"id": "grief_led", "label": "Emotion-led pain", "hint": "Affective channel dominant"},
        ],
        "metrics": [
            {"id": "qualifies", "label": "IASP pain?", "tone": "pain"},
            {"id": "fusion", "label": "fused intensity", "tone": "gold"},
        ],
    },
    {
        "id": "fig-icd11",
        "num": "1c",
        "title": "ICD-11 MG30: seven chronic-pain categories, nested subtypes",
        "cite_url": "https://journals.lww.com/pain/fulltext/2022/02000/classification_of_chronic_pain_for_the.29.aspx",
        "cite_label": "Treede et al. 2022",
        "scene": "fig-icd11",
        "caption": "ICD-11 makes chronic pain a disease category. The alarm can outlive the fire.",
        "blurb": (
            "ICD-11 lists seven chronic pain categories because alarms persist after injuries heal. "
            "Scrub the timeline — watch the acute trigger fade while chronic classes stay lit."
        ),
        "control_prompt": "Scrub the clinical timeline:",
        "scrub": {"id": "months", "label": "Months since injury", "min": 0, "max": 24, "value": 0, "unit": "mo"},
        "metrics": [
            {"id": "injury", "label": "acute trigger", "tone": "gold"},
            {"id": "branches", "label": "MG30 classes lit", "tone": "pain"},
        ],
    },
    {
        "id": "fig-mcgill",
        "num": "1d",
        "title": "McGill MPQ: 78 words because pain factorizes in language",
        "cite_url": "https://pubmed.ncbi.nlm.nih.gov/1235985/",
        "cite_label": "Melzack 1975",
        "scene": "fig-mcgill",
        "caption": "78 pain descriptors in clinical use. Pleasure shares far fewer words.",
        "blurb": (
            "The McGill Pain Questionnaire carries 78 descriptor words across sensory, affective, "
            "evaluative, and miscellaneous domains — pleasure vocabulary stays sparse."
        ),
        "control_prompt": "Toggle lexicon view:",
        "presets": [
            {"id": "mpq_clinical", "label": "MPQ clinical (78)", "hint": "Sensory · affective · evaluative"},
            {"id": "pleasure_colloquial", "label": "Pleasure words (~12)", "hint": "Sparse everyday labels"},
        ],
        "metrics": [
            {"id": "words", "label": "visible words", "tone": "pain"},
            {"id": "ratio", "label": "pain:pleasure", "tone": "gold"},
        ],
    },
    {
        "id": "fig-price",
        "num": "1e",
        "title": "Price: sensation, unpleasantness, and secondary affect dissociate",
        "cite_url": "https://doi.org/10.1126/science.288.5472.1769",
        "cite_label": "Price 2000",
        "scene": "fig-price",
        "caption": "Intensity and unpleasantness can separate — one injury, multiple ledgers.",
        "blurb": (
            "Price separates sensory intensity, unpleasantness, and secondary affect into partially "
            "independent dimensions — one stimulus can climb one ledger while another stays flat."
        ),
        "control_prompt": "Price's dissociation cases:",
        "presets": [
            {"id": "capsaicin", "label": "Capsaicin on tongue", "hint": "High intensity · lower unpleasantness"},
            {"id": "colic", "label": "Labor / colic", "hint": "All three ledgers climb"},
            {"id": "neuropathic", "label": "Neuropathic sting", "hint": "Low intensity · high suffering"},
        ],
        "metrics": [
            {"id": "layers", "label": "ledgers active", "tone": "pain"},
            {"id": "dissoc", "label": "dissociation", "tone": "gold"},
        ],
    },
    {
        "id": "fig-berridge",
        "num": "2a",
        "title": "Berridge: small “liking” hotspots, sprawling “wanting” system",
        "cite_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4425246/",
        "cite_label": "Berridge & Kringelbach 2015",
        "scene": "fig-berridge",
        "caption": "Wanting ≠ liking. Pleasure clusters; pursuit can run without joy.",
        "blurb": (
            "Berridge: hedonic \"liking\" sits in tight opioid hotspots; dopaminergic \"wanting\" sprawls. "
            "Addiction often decouples pursuit from felt joy."
        ),
        "control_prompt": "Compare reward states:",
        "presets": [
            {"id": "healthy_meal", "label": "Sated meal", "hint": "Liking ≈ wanting"},
            {"id": "addiction", "label": "Addiction profile", "hint": "Wanting ≫ liking"},
            {"id": "hotspot", "label": "Direct opioid liking", "hint": "Tight hedonic cluster"},
        ],
        "metrics": [
            {"id": "orbit", "label": "wanting spread", "tone": "gold"},
            {"id": "cluster", "label": "liking intensity", "tone": "pleasure"},
        ],
    },
    {
        "id": "fig-leknes",
        "num": "2b",
        "title": "Leknes & Tracey: shared opioid/dopamine substrate — substitutability",
        "cite_url": "https://www.nature.com/articles/nrn2333",
        "cite_label": "Leknes & Tracey 2008",
        "scene": "fig-leknes",
        "caption": "Relief is pleasure with a history of threat — green borrows from red.",
        "blurb": (
            "Relief-affect rides the same substrates as threat processing. "
            "Stopping pain feels good because the system was recently under threat."
        ),
        "control_prompt": "Relief vs prior threat:",
        "presets": [
            {"id": "mild_relief", "label": "Minor annoyance ends", "hint": "Weak threat → weak relief"},
            {"id": "burn_relief", "label": "Burn then cool water", "hint": "High threat → strong relief"},
            {"id": "chronic", "label": "Chronic threat", "hint": "Relief exhausted"},
        ],
        "metrics": [
            {"id": "relief", "label": "relief felt", "tone": "pleasure"},
            {"id": "residual", "label": "threat residue", "tone": "pain"},
        ],
    },
    {
        "id": "fig-baumeister",
        "num": "3a",
        "title": "Baumeister: bad is stronger than good across domains",
        "cite_url": "https://doi.org/10.1037/1089-2680.5.4.323",
        "cite_label": "Baumeister et al. 2001",
        "scene": "fig-baumeister",
        "caption": "Bad events outweigh matched good ones. Harm writes in heavier ink.",
        "blurb": (
            "Baumeister's review: matched bad events outweigh good ones in learning, memory, and impression "
            "formation — an empirical asymmetry, not a moral claim."
        ),
        "control_prompt": "Matched events on the scale:",
        "presets": [
            {"id": "one_compliment", "label": "One compliment", "hint": "Light tilt"},
            {"id": "one_insult", "label": "One insult", "hint": "Heavy tilt (~2–5×)"},
            {"id": "paired", "label": "Same-day pair", "hint": "Bad dominates net memory"},
        ],
        "metrics": [
            {"id": "tilt", "label": "bad:good weight", "tone": "gold"},
            {"id": "net", "label": "remembered valence", "tone": "pain"},
        ],
    },
    {
        "id": "fig-rozin",
        "num": "3b",
        "title": "Rozin & Royzman: negative differentiation — suffering is more varied",
        "cite_url": "https://doi.org/10.1207/S15327957PSPR0504_2",
        "cite_label": "Rozin & Royzman 2001",
        "scene": "fig-rozin",
        "caption": "Bad spreads to neighbors and meaning. Good stays local.",
        "blurb": (
            "Negative differentiation: bad is richer and more contagious than good. "
            "One contamination stains adjacent categories; good events stay local."
        ),
        "control_prompt": "Contamination stages:",
        "presets": [
            {"id": "clean", "label": "Before event", "hint": "Neutral grid"},
            {"id": "one_drop", "label": "One bad event", "hint": "Local stain"},
            {"id": "spread", "label": "After rumination", "hint": "Bad infects neighbors"},
        ],
        "metrics": [
            {"id": "spread", "label": "stained nodes", "tone": "pain"},
            {"id": "isolated", "label": "good enclaves", "tone": "pleasure"},
        ],
    },
    {
        "id": "fig-eisenberger",
        "num": "3c",
        "title": "Eisenberger: social pain without peripheral nociception",
        "cite_url": "https://pubmed.ncbi.nlm.nih.gov/14500928/",
        "cite_label": "Eisenberger et al. 2003",
        "scene": "fig-eisenberger",
        "caption": "Social exclusion recruits the same circuits as bodily hurt.",
        "blurb": (
            "Cyberball exclusion activates dACC and insula — overlap with physical pain circuitry "
            "without peripheral nociception."
        ),
        "control_prompt": "Cyberball conditions:",
        "presets": [
            {"id": "included", "label": "Included throws", "hint": "dACC quiet"},
            {"id": "excluded", "label": "Excluded (Cyberball)", "hint": "dACC lights up"},
        ],
        "metrics": [
            {"id": "acc", "label": "dACC activation", "tone": "pain"},
            {"id": "overlap", "label": "body-circuit overlap", "tone": "gold"},
        ],
    },
    {
        "id": "fig-lazarus",
        "num": "3d",
        "title": "Lazarus: same stressor, different suffering by appraisal frame",
        "cite_url": "https://archive.org/details/stressappraisalc0000laza",
        "cite_label": "Lazarus & Folkman 1984",
        "scene": "fig-lazarus",
        "caption": "Appraisal transforms the event: threat, blame, and coping change the felt blow.",
        "blurb": (
            "Same objective stressor — different primary appraisal (threat vs challenge) — "
            "different suffering output. The frame is part of the injury."
        ),
        "control_prompt": "Same stressor, different frame:",
        "presets": [
            {"id": "threat", "label": "Threat + self-blame", "hint": "High suffering path"},
            {"id": "challenge", "label": "Challenge + resources", "hint": "Lower suffering path"},
        ],
        "metrics": [
            {"id": "output_a", "label": "threat output", "tone": "pain"},
            {"id": "output_b", "label": "challenge output", "tone": "pleasure"},
        ],
    },
]

PMX: list[Widget] = [
    {
        "id": "pmx-00",
        "num": "W0",
        "title": "The warranty card in the crib",
        "scene": "pmx-00",
        "caption": "Every civilization assigns repair rights and forbids exit from the inherited human format before consent is possible.",
        "blurb": (
            "Homo sapiens ships with known defects — pain, fear, grief, decay, death — and no consent form."
        ),
        "control_prompt": "View the warranty:",
        "presets": [
            {"id": "defects", "label": "Known defects", "hint": "Shipped at birth"},
            {"id": "regimes", "label": "Three exit locks", "hint": "Repair OK · exit forbidden"},
        ],
        "metrics": [
            {"id": "defects_n", "label": "listed defects", "tone": "pain"},
            {"id": "locks", "label": "exit locks", "tone": "gold"},
        ],
    },
    {
        "id": "pmx-03",
        "num": "W3",
        "title": "Genesis as QA report",
        "scene": "pmx-03",
        "caption": "Birth pain, toil, mortality — hardware bugs logged before moral billing.",
        "blurb": "Genesis 2–3 as a defect table logged before the operator is blamed.",
        "control_prompt": "Read the defect log:",
        "presets": [
            {"id": "logged", "label": "Defects logged", "hint": "Birth pain · toil · death"},
            {"id": "blame_shift", "label": "Blame assigned", "hint": "Fault moves to user"},
        ],
        "metrics": [
            {"id": "defects", "label": "open defects", "tone": "pain"},
            {"id": "blame", "label": "user blame %", "tone": "gold"},
        ],
    },
    {
        "id": "pmx-04",
        "num": "W4",
        "title": "Original sin inversion",
        "scene": "pmx-04",
        "caption": "Blame vectors flip: from disobedient user to negligent manufacturer.",
        "blurb": "Original Sin as manufacture, not disobedience — fault moves upstream.",
        "control_prompt": "Where does fault live?",
        "presets": [
            {"id": "traditional", "label": "Traditional reading", "hint": "User disobeyed"},
            {"id": "manufacture", "label": "Manufacture reading", "hint": "Design defect"},
        ],
        "metrics": [
            {"id": "upstream", "label": "design fault", "tone": "pain"},
            {"id": "downstream", "label": "user fault", "tone": "muted"},
        ],
    },
    {
        "id": "pmx-09",
        "num": "W9",
        "title": "Three warranty regimes",
        "scene": "pmx-09",
        "caption": "Christianity, Islam, secular humanism — repair yes, exit no.",
        "blurb": "Three theologies · one body policy: repair the chassis, never abandon it.",
        "control_prompt": "Try an exit attempt:",
        "presets": [
            {"id": "repair_ok", "label": "Medical repair", "hint": "All regimes allow"},
            {"id": "exit_attempt", "label": "Morphological exit", "hint": "All regimes veto"},
        ],
        "metrics": [
            {"id": "aligned", "label": "regimes aligned", "tone": "gold"},
            {"id": "veto", "label": "exit blocked", "tone": "pain"},
        ],
    },
    {
        "id": "pmx-05",
        "num": "W5",
        "title": "Mandate ladder: therapy to exit",
        "scene": "pmx-05",
        "caption": "Medicine climbs the ladder; morphological exit hits the wall.",
        "blurb": "Therapy and enhancement climb; lawful exit from biology hits a guarded ceiling.",
        "control_prompt": "Climb the warrantied ladder:",
        "presets": [
            {"id": "therapy", "label": "Therapy rung", "hint": "Approved"},
            {"id": "enhance", "label": "Enhancement rung", "hint": "Approved"},
            {"id": "exit", "label": "Exit attempt", "hint": "Wall"},
        ],
        "metrics": [
            {"id": "rung", "label": "ladder rung", "tone": "gold"},
            {"id": "wall", "label": "wall hit?", "tone": "pain"},
        ],
    },
    {
        "id": "pmx-11",
        "num": "WB",
        "title": "Suffering audit dashboard",
        "scene": "pmx-11",
        "caption": "Target: involuntary suffering → zero. Abolition as engineering metric.",
        "blurb": "Involuntary suffering as an engineering defect with a measurable audit trail.",
        "control_prompt": "Audit era:",
        "presets": [
            {"id": "status_quo", "label": "Status quo", "hint": "High involuntary harm"},
            {"id": "audit_on", "label": "Audit deployed", "hint": "Harm tracked ↓"},
            {"id": "target", "label": "Abolition target", "hint": "→ 0 involuntary"},
        ],
        "metrics": [
            {"id": "involuntary", "label": "involuntary %", "tone": "pain"},
            {"id": "trajectory", "label": "audit score", "tone": "pleasure"},
        ],
    },
]

ALL_WIDGETS = CLINICAL + PMX


def _preset_html(p: dict[str, str]) -> str:
    pid = html.escape(p["id"])
    label = html.escape(p["label"])
    hint = html.escape(p.get("hint", ""))
    return f'        <button type="button" class="pm-ev-preset" data-preset="{pid}" title="{hint}">{label}</button>'


def _scrub_html(scrub: dict[str, Any]) -> str:
    sid = html.escape(scrub["id"])
    label = html.escape(scrub["label"])
    mn = scrub.get("min", 0)
    mx = scrub.get("max", 100)
    val = scrub.get("value", mn)
    unit = html.escape(scrub.get("unit", ""))
    return f"""        <div class="pm-ev-scrub">
          <label>{label} <b data-scrub-val="{sid}">{val}</b>{f" {unit}" if unit else ""}</label>
          <input type="range" min="{mn}" max="{mx}" value="{val}" data-scrub="{sid}">
        </div>"""


def _metric_html(m: dict[str, str]) -> str:
    mid = html.escape(m["id"])
    tone = html.escape(m.get("tone", "gold"))
    label = html.escape(m["label"])
    return f'          <div class="pm-ev-metric {tone}"><b data-m="{mid}">—</b><span>{label}</span></div>'


def widget_html(w: Widget) -> str:
    cite = ""
    if w.get("cite_url"):
        cite = (
            f'\n    <a class="pm-cite" href="{html.escape(w["cite_url"])}">'
            f'{html.escape(w["cite_label"])}</a>'
        )
    presets = "\n".join(_preset_html(p) for p in w.get("presets", []))
    scrub = _scrub_html(w["scrub"]) if w.get("scrub") else ""
    metrics = "\n".join(_metric_html(m) for m in w.get("metrics", []))
    blurb = html.escape(w["blurb"])
    caption = html.escape(w["caption"])
    title = html.escape(w["title"])
    num = html.escape(w["num"])
    fid = html.escape(w["id"])
    scene = html.escape(w["scene"])
    prompt = html.escape(w.get("control_prompt", "Compare cases:"))
    default_preset = html.escape(w["presets"][0]["id"]) if w.get("presets") else ""

    preset_block = ""
    if presets:
        preset_block = f"""        <p class="pm-ev-prompt">{prompt}</p>
        <div class="pm-ev-presets" data-default="{default_preset}">
{presets}
        </div>"""

    return f"""<figure class="pm-fig pm-fig-evidence" id="{fid}">
  <div class="pm-fig-head">
    <span class="pm-fig-n">{num}</span>
    <h4>{title}</h4>{cite}
  </div>
  <div class="pm-evidence" data-scene="{scene}">
    <div class="pm-ev-layout">
      <div class="pm-ev-view">
        <canvas class="pm-ev-canvas" aria-hidden="true"></canvas>
        <div class="pm-ev-labels" aria-hidden="true"></div>
        <div class="pm-ev-hud">
{metrics}
        </div>
        <div class="pm-ev-readout" data-readout></div>
      </div>
      <div class="pm-ev-panel">
{preset_block}{scrub}
        <p class="pm-ev-lesson" data-lesson></p>
        <p class="pm-ev-blurb">{blurb}</p>
      </div>
    </div>
  </div>
  <p class="pm-fig-cap">{caption}</p>
</figure>"""
