#!/usr/bin/env python3
"""Generate interactive Three.js evidence widgets for Pain Machines figures."""

from __future__ import annotations

import html
import json
from typing import Any

Widget = dict[str, Any]

CLINICAL: list[Widget] = [
    {
        "id": "fig-neuromatrix",
        "num": "1a",
        "title": "Neuromatrix: pain generated by the whole brain",
        "cite_url": "https://pubmed.ncbi.nlm.nih.gov/11780656/",
        "cite_label": "Melzack 2001",
        "scene": "fig-neuromatrix",
        "caption": "Melzack broke the courtroom model: the brain builds pain from signal, map, memory, stress, and expectation.",
        "blurb": (
            "Melzack's neuromatrix theory treats pain as a distributed output pattern — not a faithful "
            "meter of tissue damage. Somatic input is one contributor among memory traces, stress gates, "
            "and appraisal. Phantom-limb pain is the proof case: the map persists after the limb is gone."
        ),
        "sliders": [
            {"id": "somatic", "label": "somatic input", "value": 55, "tone": "pain"},
            {"id": "memory", "label": "memory load", "value": 72, "tone": "pain"},
            {"id": "stress", "label": "stress gate", "value": 68, "tone": "pain"},
        ],
        "metrics": [
            {"id": "output", "label": "pain output", "tone": "pain"},
            {"id": "inputs", "label": "active inputs", "tone": "gold"},
        ],
    },
    {
        "id": "fig-iasp",
        "num": "1b",
        "title": "IASP 2020: sensory and emotional are inseparable",
        "cite_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC7680716/",
        "cite_label": "Raja et al. 2020",
        "scene": "fig-iasp",
        "caption": "Official medicine: pain is always sensory and emotional — not a tissue meter alone.",
        "blurb": (
            "The 2020 IASP revision defines pain as \"an unpleasant sensory and emotional experience.\" "
            "Clinicians cannot strip the affective channel without losing the diagnosis. Body-signal and "
            "emotion are co-primary, not optional add-ons."
        ),
        "sliders": [
            {"id": "sensory", "label": "sensory channel", "value": 80, "tone": "pain"},
            {"id": "affective", "label": "emotional channel", "value": 75, "tone": "gold"},
        ],
        "metrics": [
            {"id": "fusion", "label": "fused intensity", "tone": "pain"},
            {"id": "ratio", "label": "sensory/affect", "tone": "gold"},
        ],
    },
    {
        "id": "fig-icd11",
        "num": "1c",
        "title": "ICD-11 MG30: seven chronic-pain categories, nested subtypes",
        "cite_url": "https://journals.lww.com/pain/fulltext/2022/02000/classification_of_chronic_pain_for_the.29.aspx",
        "cite_label": "Treede et al. 2022",
        "scene": "fig-icd11",
        "caption": "ICD-11 makes chronic pain a disease category. The alarm can outlive the fire.",
        "blurb": (
            "ICD-11 lists seven chronic primary and secondary pain categories with nested subtypes. "
            "The taxonomy exists because alarms persist after injuries heal — chronic pain is classified "
            "as its own disease process, not merely a symptom timer."
        ),
        "sliders": [
            {"id": "injury", "label": "initial injury", "value": 90, "tone": "pain"},
            {"id": "persistence", "label": "alarm persistence", "value": 70, "tone": "gold"},
        ],
        "metrics": [
            {"id": "branches", "label": "active categories", "tone": "pain"},
            {"id": "lag", "label": "alarm lag (mo)", "tone": "gold"},
        ],
    },
    {
        "id": "fig-mcgill",
        "num": "1d",
        "title": "McGill MPQ: 78 words because pain factorizes in language",
        "cite_url": "https://pubmed.ncbi.nlm.nih.gov/1235985/",
        "cite_label": "Melzack 1975",
        "scene": "fig-mcgill",
        "caption": "78 pain descriptors in clinical use. Pleasure shares far fewer words.",
        "blurb": (
            "The McGill Pain Questionnaire carries 78 descriptor words across sensory, affective, "
            "evaluative, and miscellaneous domains. Language factorizes pain into many axes; pleasure "
            "vocabulary stays sparse — a lexical asymmetry clinicians already encode."
        ),
        "sliders": [
            {"id": "pain_lex", "label": "pain descriptors", "value": 78, "min": 20, "max": 78, "tone": "pain"},
            {"id": "pleas_lex", "label": "pleasure descriptors", "value": 12, "min": 4, "max": 24, "tone": "pleasure"},
        ],
        "metrics": [
            {"id": "ratio", "label": "word ratio", "tone": "gold"},
            {"id": "density", "label": "pain density", "tone": "pain"},
        ],
    },
    {
        "id": "fig-price",
        "num": "1e",
        "title": "Price: sensation, unpleasantness, and secondary affect dissociate",
        "cite_url": "https://doi.org/10.1126/science.288.5472.1769",
        "cite_label": "Price 2000",
        "scene": "fig-price",
        "caption": "Intensity and unpleasantness can separate — one injury, multiple ledgers.",
        "blurb": (
            "Price's psychophysical work separates sensory intensity, unpleasantness, and secondary affect "
            "into partially independent dimensions. One stimulus can climb one ledger while another stays flat — "
            "evidence against a single pain dial."
        ),
        "sliders": [
            {"id": "intensity", "label": "sensory intensity", "value": 70, "tone": "pain"},
            {"id": "unpleasant", "label": "unpleasantness", "value": 85, "tone": "pain"},
            {"id": "secondary", "label": "secondary affect", "value": 60, "tone": "gold"},
        ],
        "metrics": [
            {"id": "layers", "label": "active layers", "tone": "pain"},
            {"id": "pleasure", "label": "pleasure band", "tone": "pleasure"},
        ],
    },
    {
        "id": "fig-berridge",
        "num": "2a",
        "title": "Berridge: small “liking” hotspots, sprawling “wanting” system",
        "cite_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4425246/",
        "cite_label": "Berridge & Kringelbach 2015",
        "scene": "fig-berridge",
        "caption": "Wanting ≠ liking. Pleasure clusters; pursuit can run without joy.",
        "blurb": (
            "Berridge distinguishes hedonic \"liking\" (tight opioid hotspots in NAc shell and VP) from "
            "dopaminergic \"wanting\" that sprawls across mesolimbic circuitry. Addiction often decouples "
            "pursuit from felt joy — more runway for compulsion than for pleasure."
        ),
        "sliders": [
            {"id": "wanting", "label": "wanting drive", "value": 78, "tone": "gold"},
            {"id": "liking", "label": "liking hotspots", "value": 35, "tone": "pleasure"},
        ],
        "metrics": [
            {"id": "orbit", "label": "wanting radius", "tone": "gold"},
            {"id": "cluster", "label": "liking cluster", "tone": "pleasure"},
        ],
    },
    {
        "id": "fig-leknes",
        "num": "2b",
        "title": "Leknes & Tracey: shared opioid/dopamine substrate — substitutability",
        "cite_url": "https://www.nature.com/articles/nrn2333",
        "cite_label": "Leknes & Tracey 2008",
        "scene": "fig-leknes",
        "caption": "Relief is pleasure with a history of threat — green borrows from red.",
        "blurb": (
            "Relief-affect rides the same opioid and dopamine substrates as threat processing. "
            "Stopping pain feels good because the system was recently under threat — pleasure here "
            "is often the shadow of avoided harm, not a symmetric opposite."
        ),
        "sliders": [
            {"id": "threat", "label": "prior threat", "value": 75, "tone": "pain"},
            {"id": "relief", "label": "relief spike", "value": 55, "tone": "pleasure"},
        ],
        "metrics": [
            {"id": "borrow", "label": "borrowed pleasure", "tone": "pleasure"},
            {"id": "residual", "label": "threat residue", "tone": "pain"},
        ],
    },
    {
        "id": "fig-baumeister",
        "num": "3a",
        "title": "Baumeister: bad is stronger than good across domains",
        "cite_url": "https://doi.org/10.1037/1089-2680.5.4.323",
        "cite_label": "Baumeister et al. 2001",
        "scene": "fig-baumeister",
        "caption": "Bad events outweigh matched good ones. Harm writes in heavier ink.",
        "blurb": (
            "Baumeister's review finds bad events, emotions, and impressions carry more weight than "
            "matched good ones across psychology — from learning rates to relationship memory. The scale "
            "tilts without any moral claim; it's an empirical asymmetry in how minds update."
        ),
        "sliders": [
            {"id": "bad", "label": "harm weight", "value": 82, "tone": "pain"},
            {"id": "good", "label": "benefit weight", "value": 38, "tone": "pleasure"},
        ],
        "metrics": [
            {"id": "tilt", "label": "tilt ratio", "tone": "gold"},
            {"id": "net", "label": "net valence", "tone": "pain"},
        ],
    },
    {
        "id": "fig-rozin",
        "num": "3b",
        "title": "Rozin & Royzman: negative differentiation — suffering is more varied",
        "cite_url": "https://doi.org/10.1207/S15327957PSPR0504_2",
        "cite_label": "Rozin & Royzman 2001",
        "scene": "fig-rozin",
        "caption": "Bad spreads to neighbors and meaning. Good stays local.",
        "blurb": (
            "Negative differentiation: the bad domain is richer, more differentiated, and more contagious "
            "than the good. One contamination event stains adjacent categories; good events rarely "
            "propagate the same way — negativity dominance in cognitive structure."
        ),
        "sliders": [
            {"id": "contagion", "label": "contagion radius", "value": 72, "tone": "pain"},
            {"id": "good_local", "label": "good locality", "value": 28, "tone": "pleasure"},
        ],
        "metrics": [
            {"id": "spread", "label": "infected nodes", "tone": "pain"},
            {"id": "isolated", "label": "good enclaves", "tone": "pleasure"},
        ],
    },
    {
        "id": "fig-eisenberger",
        "num": "3c",
        "title": "Eisenberger: social pain without peripheral nociception",
        "cite_url": "https://pubmed.ncbi.nlm.nih.gov/14500928/",
        "cite_label": "Eisenberger et al. 2003",
        "scene": "fig-eisenberger",
        "caption": "Social exclusion recruits the same circuits as bodily hurt.",
        "blurb": (
            "Cyberball exclusion activates dACC and insula — overlap with physical pain circuitry "
            "without peripheral nociception. Social injury is not metaphorical in the brain; it uses "
            "hardware evolved for bodily threat."
        ),
        "sliders": [
            {"id": "exclusion", "label": "exclusion intensity", "value": 70, "tone": "pain"},
            {"id": "belonging", "label": "group acceptance", "value": 40, "tone": "pleasure"},
        ],
        "metrics": [
            {"id": "acc", "label": "dACC activation", "tone": "pain"},
            {"id": "overlap", "label": "body overlap", "tone": "gold"},
        ],
    },
    {
        "id": "fig-lazarus",
        "num": "3d",
        "title": "Lazarus: same stressor, different suffering by appraisal frame",
        "cite_url": "https://archive.org/details/stressappraisalc0000laza",
        "cite_label": "Lazarus & Folkman 1984",
        "scene": "fig-lazarus",
        "caption": "Appraisal transforms the event: threat, blame, and coping change the felt blow.",
        "blurb": (
            "Lazarus–Folkman stress appraisal: primary appraisal (harm/threat/challenge) and secondary "
            "appraisal (coping resources) reshape the same objective stressor into different suffering "
            "outputs — the event is not the whole story; the frame is."
        ),
        "sliders": [
            {"id": "threat", "label": "threat frame", "value": 75, "tone": "pain"},
            {"id": "challenge", "label": "challenge frame", "value": 35, "tone": "pleasure"},
            {"id": "blame", "label": "self-blame", "value": 60, "tone": "gold"},
        ],
        "metrics": [
            {"id": "output_a", "label": "threat path", "tone": "pain"},
            {"id": "output_b", "label": "challenge path", "tone": "pleasure"},
        ],
    },
]

PMX: list[Widget] = [
    {
        "id": "pmx-00",
        "num": "W0",
        "title": "The warranty card in the crib",
        "scene": "pmx-00",
        "caption": "Every civilization assigns repair rights and forbids exit from the inherited human format before consent is possible.",
        "blurb": (
            "Homo sapiens ships with known defects — pain, fear, grief, decay, death — and no consent form. "
            "Christian, Islamic, and secular regimes disagree on metaphysics but converge on the clause: "
            "repair the chassis, never abandon it."
        ),
        "sliders": [
            {"id": "defects", "label": "defect severity", "value": 85, "tone": "pain"},
            {"id": "repair", "label": "repair mandate", "value": 70, "tone": "gold"},
        ],
        "metrics": [
            {"id": "locks", "label": "exit locks", "tone": "pain"},
            {"id": "regimes", "label": "aligned regimes", "tone": "gold"},
        ],
    },
    {
        "id": "pmx-03",
        "num": "W3",
        "title": "Genesis as QA report",
        "scene": "pmx-03",
        "caption": "Birth pain, toil, mortality — hardware bugs logged before moral billing.",
        "blurb": (
            "Genesis 2–3 reads like a defect table: birth pain, agricultural toil, mortality, shame — "
            "logged as product behavior before the user is blamed. The narrative inverts warranty law: "
            "fault moves downstream to the operator."
        ),
        "sliders": [
            {"id": "bugs", "label": "defect cascade", "value": 80, "tone": "pain"},
            {"id": "blame", "label": "user blame", "value": 65, "tone": "gold"},
        ],
        "metrics": [
            {"id": "defects", "label": "open defects", "tone": "pain"},
            {"id": "severity", "label": "severity index", "tone": "gold"},
        ],
    },
    {
        "id": "pmx-04",
        "num": "W4",
        "title": "Original sin inversion",
        "scene": "pmx-04",
        "caption": "Blame vectors flip: from disobedient user to negligent manufacturer.",
        "blurb": (
            "Original Sin reframed as manufacture, not disobedience: consciousness was built inside a "
            "pain machine, then the operator was invoiced. The inversion moves moral fault upstream — "
            "from appetite to design."
        ),
        "sliders": [
            {"id": "user_blame", "label": "user blame", "value": 30, "tone": "muted"},
            {"id": "design_blame", "label": "design blame", "value": 88, "tone": "pain"},
        ],
        "metrics": [
            {"id": "upstream", "label": "upstream fault", "tone": "pain"},
            {"id": "downstream", "label": "user fault", "tone": "muted"},
        ],
    },
    {
        "id": "pmx-09",
        "num": "W9",
        "title": "Three warranty regimes",
        "scene": "pmx-09",
        "caption": "Christianity, Islam, secular humanism — repair yes, exit no.",
        "blurb": (
            "Three traditions with incompatible theologies share one body policy: sanctify or steward the "
            "flesh, forbid self-destruction, veto posthuman exit. Repair is sacred; escape is profane or "
            "undignified — the lock is structural, not sectarian."
        ),
        "sliders": [
            {"id": "repair", "label": "repair allowance", "value": 85, "tone": "gold"},
            {"id": "exit", "label": "exit attempt", "value": 15, "tone": "pain"},
        ],
        "metrics": [
            {"id": "aligned", "label": "regime alignment", "tone": "gold"},
            {"id": "veto", "label": "exit veto", "tone": "pain"},
        ],
    },
    {
        "id": "pmx-05",
        "num": "W5",
        "title": "Mandate ladder: therapy to exit",
        "scene": "pmx-05",
        "caption": "Medicine climbs the ladder; morphological exit hits the wall.",
        "blurb": (
            "The warrantied path runs therapy → enhancement → morphological repair — each rung approved. "
            "Lawful exit from biology itself hits a ceiling every regime guards. The mandate is to finish "
            "the ladder without manufacturing new hells."
        ),
        "sliders": [
            {"id": "therapy", "label": "therapy climb", "value": 75, "tone": "gold"},
            {"id": "exit", "label": "exit pressure", "value": 55, "tone": "pain"},
        ],
        "metrics": [
            {"id": "rung", "label": "ladder rung", "tone": "gold"},
            {"id": "wall", "label": "wall height", "tone": "pain"},
        ],
    },
    {
        "id": "pmx-11",
        "num": "WB",
        "title": "Suffering audit dashboard",
        "scene": "pmx-11",
        "caption": "Target: involuntary suffering → zero. Abolition as engineering metric.",
        "blurb": (
            "Treat involuntary suffering as an engineering defect with a measurable audit trail. "
            "The abolition target is not utopian mood — it is driving preventable harm states toward "
            "zero without creating new captive minds."
        ),
        "sliders": [
            {"id": "audit", "label": "audit intensity", "value": 70, "tone": "gold"},
            {"id": "residual", "label": "residual harm", "value": 45, "tone": "pain"},
        ],
        "metrics": [
            {"id": "involuntary", "label": "involuntary %", "tone": "pain"},
            {"id": "trajectory", "label": "↓ trajectory", "tone": "pleasure"},
        ],
    },
]

ALL_WIDGETS = CLINICAL + PMX


def _slider_html(sl: dict[str, Any]) -> str:
    tone = sl.get("tone", "pain")
    mn = sl.get("min", 0)
    mx = sl.get("max", 100)
    val = sl.get("value", 50)
    sid = html.escape(sl["id"])
    label = html.escape(sl["label"])
    return f"""        <div class="pm-ev-slider {tone}">
          <label>{label} <b data-slider-val="{sid}">{val}</b></label>
          <input type="range" min="{mn}" max="{mx}" value="{val}" data-slider="{sid}">
        </div>"""


def _metric_html(m: dict[str, str]) -> str:
    mid = html.escape(m["id"])
    tone = html.escape(m.get("tone", "gold"))
    label = html.escape(m["label"])
    return f'          <div class="pm-ev-metric {tone}"><b data-m="{mid}">—</b><span>{label}</span></div>'


def widget_html(w: Widget) -> str:
    cite = ""
    if w.get("cite_url"):
        cite = (
            f'\n    <a class="pm-cite" href="{html.escape(w["cite_url"])}">'
            f'{html.escape(w["cite_label"])}</a>'
        )
    sliders = "\n".join(_slider_html(s) for s in w.get("sliders", []))
    metrics = "\n".join(_metric_html(m) for m in w.get("metrics", []))
    blurb = html.escape(w["blurb"])
    caption = html.escape(w["caption"])
    title = html.escape(w["title"])
    num = html.escape(w["num"])
    fid = html.escape(w["id"])
    scene = html.escape(w["scene"])

    return f"""<figure class="pm-fig pm-fig-evidence" id="{fid}">
  <div class="pm-fig-head">
    <span class="pm-fig-n">{num}</span>
    <h4>{title}</h4>{cite}
  </div>
  <div class="pm-evidence" data-scene="{scene}">
    <div class="pm-ev-layout">
      <div class="pm-ev-view">
        <canvas class="pm-ev-canvas" aria-hidden="true"></canvas>
        <div class="pm-ev-labels" aria-hidden="true"></div>
        <div class="pm-ev-hud">
{metrics}
        </div>
        <div class="pm-ev-readout" data-readout></div>
      </div>
      <div class="pm-ev-panel">
        <h5>Live controls</h5>
        <div class="pm-ev-controls">
{sliders}
        </div>
        <p class="pm-ev-blurb">{blurb}</p>
      </div>
    </div>
  </div>
  <p class="pm-fig-cap">{caption}</p>
</figure>"""


def widgets_for(ids: list[str] | None = None) -> str:
    lookup = {w["id"]: w for w in ALL_WIDGETS}
    if ids:
        return "".join(widget_html(lookup[i]) for i in ids if i in lookup)
    return "".join(widget_html(w) for w in ALL_WIDGETS)


def scene_index_json() -> str:
    index = {w["scene"]: w["id"] for w in ALL_WIDGETS}
    return json.dumps(index)
